export interface SearchContentProps {
  Id: string;
  Type: string;
  Name: string;
  Icon: string;
  DeleteIcon: string;
}

export const SearchContent = [
  {
    Id: '0',
    Type: 'previous-search',
    Name: 'Search history 1',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '1',
    Type: 'previous-search',
    Name: 'Search history 2',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '2',
    Type: 'previous-search',
    Name: 'Search history 3',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '3',
    Type: 'suggestions',
    Name: 'Search suggestions 1',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '4',
    Type: 'suggestions',
    Name: 'Search suggestions 2',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '5',
    Type: 'suggestions',
    Name: 'Search suggestions 3',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '6',
    Type: 'suggestions',
    Name: 'Search suggestions 4',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '7',
    Type: 'suggestions',
    Name: 'Search suggestions 5',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '8',
    Type: 'suggestions',
    Name: 'Search suggestions 6',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '9',
    Type: 'suggestions',
    Name: 'Search suggestions 7',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    Id: '10',
    Type: 'suggestions',
    Name: 'Search suggestions 8',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
];

export const SearchMobileContent = [
  {
    Id: '0',
    Type: 'previous-search',
    Name: 'Search history 1',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    Id: '1',
    Type: 'previous-search',
    Name: 'Search history 2',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    Id: '2',
    Type: 'previous-search',
    Name: 'Search history 3',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    Id: '3',
    Type: 'previous-search',
    Name: 'Search history 4',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    Id: '4',
    Type: 'previous-search',
    Name: 'Search history 5',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    Id: '5',
    Type: 'previous-search',
    Name: 'Search history 6',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    Id: '6',
    Type: 'suggestions',
    Name: 'Search suggestions 1',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '7',
    Type: 'suggestions',
    Name: 'Search suggestions 2',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '8',
    Type: 'suggestions',
    Name: 'Search suggestions 3',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '9',
    Type: 'suggestions',
    Name: 'Search suggestions 4',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '10',
    Type: 'suggestions',
    Name: 'Search suggestions 5',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '11',
    Type: 'suggestions',
    Name: 'Search suggestions 6',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '12',
    Type: 'suggestions',
    Name: 'Search suggestions 7',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '13',
    Type: 'suggestions',
    Name: 'Search suggestions 8',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '14',
    Type: 'suggestions',
    Name: 'Search suggestions 9',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '15',
    Type: 'suggestions',
    Name: 'Search suggestions 10',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '16',
    Type: 'suggestions',
    Name: 'Search suggestions 11',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '17',
    Type: 'suggestions',
    Name: 'Search suggestions 12',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '18',
    Type: 'suggestions',
    Name: 'Search suggestions 13',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '19',
    Type: 'suggestions',
    Name: 'Search suggestions 14',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    Id: '20',
    Type: 'suggestions',
    Name: 'Search suggestions 15',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
];
