export interface SearchContentProps {
  id: string;
  type: string;
  Name: string;
  Icon: string;
  DeleteIcon: string;
}

export const SearchContent = [
  {
    id: '0',
    type: 'previous-search',
    Name: 'Search history 1',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '1',
    type: 'previous-search',
    Name: 'Search history 2',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '2',
    type: 'previous-search',
    Name: 'Search history 3',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '3',
    type: 'suggestions',
    Name: 'Search suggestions 1',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '4',
    type: 'suggestions',
    Name: 'Search suggestions 2',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '5',
    type: 'suggestions',
    Name: 'Search suggestions 3',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '6',
    type: 'suggestions',
    Name: 'Search suggestions 4',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '7',
    type: 'suggestions',
    Name: 'Search suggestions 5',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '8',
    type: 'suggestions',
    Name: 'Search suggestions 6',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '9',
    type: 'suggestions',
    Name: 'Search suggestions 7',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
  {
    id: '10',
    type: 'suggestions',
    Name: 'Search suggestions 8',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/x-white-2.svg',
  },
];

export const SearchMobileContent = [
  {
    id: '0',
    type: 'previous-search',
    Name: 'Search history 1',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    id: '1',
    type: 'previous-search',
    Name: 'Search history 2',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    id: '2',
    type: 'previous-search',
    Name: 'Search history 3',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    id: '3',
    type: 'previous-search',
    Name: 'Search history 4',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    id: '4',
    type: 'previous-search',
    Name: 'Search history 5',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    id: '5',
    type: 'previous-search',
    Name: 'Search history 6',
    Icon: '/icons/old-search-white.svg',
    DeleteIcon: '/icons/search-delete-white.svg',
  },
  {
    id: '6',
    type: 'suggestions',
    Name: 'Search suggestions 1',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '7',
    type: 'suggestions',
    Name: 'Search suggestions 2',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '8',
    type: 'suggestions',
    Name: 'Search suggestions 3',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '9',
    type: 'suggestions',
    Name: 'Search suggestions 4',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '10',
    type: 'suggestions',
    Name: 'Search suggestions 5',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '11',
    type: 'suggestions',
    Name: 'Search suggestions 6',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '12',
    type: 'suggestions',
    Name: 'Search suggestions 7',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '13',
    type: 'suggestions',
    Name: 'Search suggestions 8',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '14',
    type: 'suggestions',
    Name: 'Search suggestions 9',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '15',
    type: 'suggestions',
    Name: 'Search suggestions 10',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '16',
    type: 'suggestions',
    Name: 'Search suggestions 11',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '17',
    type: 'suggestions',
    Name: 'Search suggestions 12',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '18',
    type: 'suggestions',
    Name: 'Search suggestions 13',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '19',
    type: 'suggestions',
    Name: 'Search suggestions 14',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
  {
    id: '20',
    type: 'suggestions',
    Name: 'Search suggestions 15',
    Icon: '/icons/search-white.svg',
    DeleteIcon: '/icons/search-arrow-white.svg',
  },
];
